### ISSUE TITLE
component scope

### ISSUE THREAD

**Issue by davidmoshal** [itsFrank/vue-typescript#8]
firstly, thanks for the excellent project, am working through the awesome-vue-typescript template.

Question: are components exported to templates or simply included by file?

from what I can see, e.g. in `awesome-vue-typescript/src/main.ts`, the components are imported once, then become available everywhere?

``` ts
import './components/navbar/navbar'
import './components/panel'
```

Thanks

**Comment by itsfrank** [comment]
Yup, just like calling `Vue.component('html-tag', {...})` in js makes `<html-tag></html-tag>` available globally, simply importing a file with the @VueComponent decorator will make the component avilable globally as well.

see https://github.com/itsFrank/vue-typescript/issues/5 for more info on scope and the status on locally scoped components

**Comment by itsfrank** [comment]
closing this since https://github.com/itsFrank/vue-typescript/issues/5 should be used for component scope

**Comment by davidmoshal** [comment]
any thoughts on hot-reloading??

**Comment by itsfrank** [comment]
Hmm, i'd have to look into the webpack settings, but i don't see why you shouldn't at least get the same benefits as a standard typescript project. Don't know about vue+webpack's hot reloading however.

In the next release, @VueExtend will be added which should make it easier to hot reload components

**Comment by davidmoshal** [comment]
I got it working!
These are the steps, roughly:
1. add `"vue-hot-reload-api": "^1.3.3",` to `package.json`
   - note: must be a version 1.x branch, master is 2.x
2. add `--hot` to the command line argument of webpack-dev-server
3. this goes in the `main.ts`
   
   ``` ts
    if( module.hot ){
        module.hot.accept()
    }
   ```
4. this goes in each file with a Vue component:  
   (TODO: I'm sure there is a way to do this one-time, in a parent component, but this works for now).
   
   So, for a LoginPanel component:
   
   ``` ts
      declare var module: any
      if( module.hot ){
           const api = require('vue-hot-reload-api')
           const Vue = require('vue')
           api.install(Vue)
           if( !module.hot.data ){
              api.createRecord('LoginPanel', LoginPanel)
           }
           else {
              api.update('LoginPanel', LoginPanel)
           }
        }
   ```
5. and this goes in the vuex store:
   
   ``` ts
       if( module.hot ){
       module.hot.accept(() =>{  // nb: add accept('mutations.js', ... if mutations in another file
              store.hotUpdate({mutations})
       })
   }
   ```

This gives you:
- Typescript
- Vue
- Vuex
- vue-typescript
- hot reloading with webpack
- vue-devtools compatiblity
- IntelliJ plugins (Typescript and Vue) compatiblity

**Comment by itsfrank** [comment]
Nice, ill try it out and see if i can't add it as an option with the decorators so you don't have to put it in every file

**Comment by itsfrank** [comment]
something like 

```
import {Config} from 'vue-typescript'
Config.hotReload = true;
```

once in main.ts before importing components should do the trick

**Comment by davidmoshal** [comment]
that would be very nice.
thanks
Dave
